#Ruta principal, osea panel de usuario
emm_user_index:
    path:     /
    defaults: { _controller: EMMUserBundle:User:index }
#Ruta para agregar usuarios
emm_user_add:
    path:     /add
    defaults: { _controller: EMMUserBundle:User:add }
#Ruta para crear un registro
emm_user_create:
    path:     /create
    defaults: { _controller: EMMUserBundle:User:create }
    methods: POST
#Ruta para editar usuarios
emm_user_edit:
    path:     /edit/{id}
    defaults: { _controller: EMMUserBundle:User:edit }
#Ruta para actualizar usuarios
emm_user_update:
    path:     /update/{id}
    defaults: { _controller: EMMUserBundle:User:update }
    methods: [POST, PUT]
#Ruta para ver usuarios
emm_user_view:
    path:     /view/{id}
    defaults: { _controller: EMMUserBundle:User:view }
#Ruta para eliminar usuarios
emm_user_delete:
    path:     /delete/{id}
    defaults: { _controller: EMMUserBundle:User:delete }
    methods: [POST, DELETE]
#Redireccionamiento
emm_user_redirect_add:
    path:     /create
    defaults: { _controller: EMMUserBundle:User:add }
#Redireccionamiento Edit
emm_user_redirect_edit:
    path:     /update/{id}
    defaults:
      _controller: EMMUserBundle:User:edit
      path: /edit
      permanent: true
#Este es simplemente un ejemplo para saber que existen funcionalidades muy buenas y utiles.
emm_user_articles:
    path:     /articles/{page}
    defaults: { _controller: EMMUserBundle:User:articles, page:1 }
    requirements:
        page: \d+
